# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = D3PDMC
PACKAGE_PRELOAD  = Hist Tree EG
PACKAGE_CXXFLAGS = -g 
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = TrigRootAnalysis atlasstyle GlobalSettings
PACKAGE_TRYDEP   = 
PACKAGE_CLEAN    = 
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0

include $(ROOTCOREDIR)/Makefile-common
