# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = D3PDData
PACKAGE_PRELOAD  = Hist Tree
PACKAGE_CXXFLAGS = -g -DINPUT_DATA
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = TrigRootAnalysis atlasstyle GlobalSettings GoodRunsLists
PACKAGE_TRYDEP   = 
PACKAGE_CLEAN    = 
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0

include $(ROOTCOREDIR)/Makefile-common